name: Build and deploy to GitHub Pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update RubyGems
        run: |
          gem update --system 3.3.22
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: "gh-pages"
          target_path: v2.0
